develop:
  extends:
    file: base.yml
    service: base
  ports:
    - "35739:35729"
  environment:
    CT_URL: http://172.30.2.63:9000 
    LOCAL_URL: http://172.30.2.63:3005
    CT_TOKEN: null
  command: develop
  volumes:
    - ./app:/opt/geojson-ms-example/app
